### ISSUE TITLE
ExternalReference union could use `Debug` implementation

### ISSUE THREAD

**Issue by bartlomieju** [denoland/rusty_v8#1268]
Right now it's not possible to print to the terminal `ExternalReference`, but it would be
very useful. I'm debugging failures in https://github.com/denoland/deno/pull/19307 and
have no way to inspect pointer addresses being passed to V8.

Since it's a `union` it's not as easy as adding `#[derive(Debug)]`, we need to provide a manual
implementation. @mmastrac any pointers here would be very appreciated.

**Comment by graham** [comment]
It looks like there is no clean way to create a descriptive debug implementation due to how unions work in Rust.

I created this diff: https://github.com/graham/rusty_v8/commit/35b4fa8daae703f2bddc874cfffb09e359d0431a

Unfortunately, it doesn't tell you anything about the current variant the union is in, but it might mean that you can #[derive(Debug)] in other structs that contain ExternalReferences.

If this seems like something that would be accepted I can create a pull request, but I'm not sure if this is helpful.

**Comment by mmastrac** [comment]
I should have marked this as closed as part of #1272 but any improvements are certainly welcome.
