### ISSUE TITLE
Expose wasi_streaming_callback

### ISSUE THREAD

**Issue by caspervonb** [denoland/rusty_v8#556]
In Deno, our implementation of `WebAssembly.instantiateStreaming` is broken because I thought the implementation provided by wasi-test-streaming would be runtime API compatible with any implementation of Response.

Turns out, from what I can tell in the implementation found here https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/wasm/wasm-js.cc#L585 that we're supposed to override wasi_streaming_callback defined here https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/isolate.h#L372

So for rusty_v8 we need Isolate to expose this callback.

**Comment by bnoordhuis** [comment]
I didn't get around to it yet but some notes in case someone wants to pick it up. Note it's a very C++-y API that doesn't map well to Rust.

Rough sketch of how the C++ API is used:
```c++
// Set: isolate->SetWasmStreamingCallback(callback);
// Called as the thenable of an internal promise.
void callback(const v8::FunctionCallbackInfo<v8::Value>& info) {
  std::shared_ptr<v8::WasmStreaming> ws = v8::WasmStreaming::Unpack(info.GetIsolate(), info.Data());
  uint8_t data[] = {0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00};
  ws->OnBytesReceived(data, sizeof(data)); // V8 copies in the data, safe to drop afterwards
  ws->Finish();
  // or:
  ws->Abort(v8::MaybeLocal<v8::Value>());
  // or:
  v8::MaybeLocal<v8::Value> exc = v8::Exception::Error(...);
  ws->Abort(exc);
}
```
Things that don't map well to Rust::

- `WasmStreaming::Unpack()` - but that's something rusty_v8 can do before forwarding to the user's callback

- `std::shared_ptr` - I think it's designed that way for async use, so it can outlive the callback, but dealing with them in Rust land is awkward.

rusty_v8 has some support for the latter by means of `v8::SharedPtr` but it doesn't implement `BorrowMut` or `DerefMut` (because shared reference) so you can't invoke mut methods, which `WasmStreaming` methods all are.

We probably need to hide the shared_ptr in a custom Rust type that's `!Clone` (and `!Sync`) and calls its destructor on drop. Something like this:
```rust
struct WasmStreaming(*mut ());

impl WasmStreaming {
  fn on_bytes_received(&mut self, data: &[u8]) { /* ... */ }
  fn finish(self) { /* ... */ } // consumes self
  fn abort(self, exception: Option<Local<Value>>) { /* ... */ }
}

impl Drop for WasmStreaming {
  fn drop(&mut self) {
    unsafe { v8__WasmStreaming__DESTRUCT(self.0) }
  }
}
```
