### ISSUE TITLE
Build failure on aarch64 when installing deno.

### ISSUE THREAD

**Issue by FlamingArr** [denoland/rusty_v8#637]
Running `cargo install deno` fails, with the following message,
```
Compiling rusty_v8 v0.20.0
error[E0308]: mismatched types
   --> .../rusty_v8-0.20.0/build.rs:150:18
    |
150 | fn platform() -> &'static str {
    |    --------      ^^^^^^^^^^^^ expected `&str`, found `()`
    |    |
    |    implicitly returns `()` as its body has no tail or `return` expression

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rusty_v8`
```

rustc and cargo version are 1.50.0.

**Comment by ry** [comment]
What's the output of `rustc --print=cfg` on your system?

**Comment by FlamingArr** [comment]
```
~ $ rustc --print=cfg
debug_assertions
target_arch="aarch64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_os="android"
target_pointer_width="64"
target_vendor="unknown"
unix
```

**Comment by ry** [comment]
There's a bit of work to do to support compiling directly on aaarch64 android. We need to provide binaries for ninja and gn. I you can get it working, patches are very welcome.

A potentially immediate workaround: try compiling with the GN and NINJA env vars set to gn and ninja binaries that you install separately. This will bypass the problematic area.

Otherwise you can also try to cross-compile rusty_v8 from a linux64 machine using `cargo build --target=aarch64-unknown-linux-gnu`

**Comment by FlamingArr** [comment]
> Otherwise you can also try to cross-compile rusty_v8 from a linux64 machine using ```cargo build --target=aarch64-unknown-linux-gnu```

I tried to cross-compile deno as a whole using that method, and when I do that, cargo gives me this error when compiling the dependancies.
```
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-unknown-linux-gnu` target may not be installed
```

**Comment by rektide** [comment]
linking to #270.
