### ISSUE TITLE
Improve Object::get_own_property_names()

### ISSUE THREAD

**Issue by bnoordhuis** [denoland/rusty_v8#740]
Refs https://github.com/denoland/deno/issues/11502.

The C++ API has a lot of flags that customize its behavior but rusty_v8 exposes none of them. It should, probably through a builder pattern, with defaults that follow the current behavior.

**Comment by augustocdias** [comment]
Hi, I'm interested in trying to tackle this issue. Where is this builder should be? In the `Context`? Or in the `HandleScope` perhaps?

The other thing that would have to be done is change the call to for example the `GetPropertyNames` to call with the full parameter list instead of the one using only the defaults correct?

**Comment by RaisinTen** [comment]
I worked on a fix for this today - https://github.com/denoland/rusty_v8/pull/1049 :)
